VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Sheet6"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Option Explicit

' アイテムメニューの型定義
Type ItemMenu
    ItemNo As Integer
    Base1No As Integer
    Base2No As Integer
    Base3No As Integer
    Base4No As Integer
    SidelineNo As Integer
    Base1Num as Integer
    Base2Num as Integer
    Base3Num as Integer
    Base4Num as Integer
    SidelineNum As Integer
    OutputNum As Integer
    Rate As Single
End Type

